import { HYDRATE } from 'next-redux-wrapper'

export const ACTION_TYPES = {
  HYDRATE,
  VALUE: 'VALUE',
  CHORD_SYMBOL: 'CHORD_SYMBOL',
  BEAT: 'BEAT',
  MIDI_NOTE_NUMBER: 'MIDI_NOTE_NUMBER',
  LOCALE: 'LOCALE',
  QUERY: 'QUERY',
  BPM: 'BPM',
  IS_DARK_MODE: 'IS_DARK_MODE',
  IS_BROWSER: 'IS_BROWSER',
  IS_DISABLED_DOWNLOAD: 'IS_DISABLED_DOWNLOAD',
  IS_DISABLED_SHARE: 'IS_DISABLED_SHARE',
  IS_HOME: 'IS_HOME',
  VERSION: 'VERSION',
  IS_SHOW_NAV: 'IS_SHOW_NAV',
} as const
