version: 2.1
orbs:
  browser-tools: circleci/browser-tools@1.1.1

executors:
  default:
    working_directory: ~/workspace
    docker:
      - image: node:14.15.5

commands:
  restore_yarn:
    steps:
      - restore_cache:
          name: Restore Yarn dependencies
          key: yarn-packages-{{ checksum "yarn.lock" }}

  save_yarn:
    steps:
      - save_cache:
          name: Cache Yarn dependencies
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/workspace/node_modules

jobs:
  setup:
    executor:
      name: default
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn install --frozen-lockfile
      - save_yarn

  lint:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - run: yarn install --frozen-lockfile
      - run: 
          name: Lint
          command: yarn lint
      - save_yarn

  build:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - run: yarn install --frozen-lockfile
      - run: 
          name: Build
          command: yarn build
      - save_yarn

  reg-suit:
    executor:
      name: default
    steps:
      - checkout
      - restore_yarn
      - browser-tools/install-chrome
      - browser-tools/install-chromedriver
      - run:
          name: Check install
          command: |
            google-chrome --version
            chromedriver --version
      - run: yarn install --frozen-lockfile
      - run: export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - run: export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - run: 
          name: Build Storybook
          command: yarn build-storybook -o dist-storybook
      - run: 
          name: StoryCap
          command: yarn storycap
      - run: 
          name: RegSuit
          command: yarn reg-suit
      - save_yarn


workflows:
  pull-request:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - lint
      - reg-suit:
          requires:
            - build